<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FocusMed.Data\FocusMed.Data.csproj" />
    <ProjectReference Include="..\FocusMed.Imaging\FocusMed.Imaging.csproj" />
    <ProjectReference Include="..\FocusMed.Printing\FocusMed.Printing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="fo-dicom" Version="5.1.2" />
    <PackageReference Include="fo-dicom.Imaging.Desktop" Version="5.1.2" />
    <PackageReference Include="fo-dicom.Codecs" Version="5.9.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
