<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\Payload2.zip">
      <LogicalName>Payload.zip</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\FocusMed.Dashboard\wwwroot\logo.png">
      <LogicalName>logo.png</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>